### PR TITLE
docs: add info about v11 and v12

### PR DESCRIPTION
**Pull request by adlazar**
Add info about v11 and v12 kernel patch series.

### CODE REVIEW

**Comment by tklengyel** [comment]
Do you have a git branch for v12 that's easy to clone? Or any plans to update this repo's submodule to that?

**Comment by Wenzel** [comment]
@adlazar could push a `kvmi-v12` branch on `KVM-VMI/kvm` and `KVM-VMI/qemu` ?

**Comment by adlazar** [comment]
Both branches are _up_, but I didn't test QEMU yet.

**Comment by adlazar** [comment]
But a stripped down version of libkvmi is needed ...

**Pull request merged**
