### PR TITLE
Vagrantfile changes

### PR DESCRIPTION
**Pull request by Soft**
- Use NFS v3 to fix strange problem described in the associated commit message.
- Add nitro prefix to VM names

### CODE REVIEW

**Comment by Wenzel** [comment]
Did you test this ?

When i was building QEMU, i had to switch to NFSv4 otherwise the build was hanging because of specific file attributes.

A makefile in QEMU was using a tool, making a syscall on the filesystem not handled by NFSv3.

**Comment by Soft** [comment]
I've been using NFS 3 with the non kvmi-branch version because I couldn't make v4 work when I was first setting this up. However, I don't remember if I had to jump through some hoops to make the VM creation phase work or if I had to do something manually.

Currently, I am still struggling to make the VM build phase work because qemu-img complaints:

```
==> qemu: Error creating hard drive: QemuImg error: qemu-img: output-qemu/ubuntu1604: Failed to lock byte 100
```
But I do not know if this is related to NFS, although now that you mention it is does seem as a likely cause for the failure. But I am still investigating.

**Comment by Soft** [comment]
Maybe it is better to keep the NFS downgrade out while I figure out what is going on

**Comment by Wenzel** [comment]
Yes, the qemu-img locking is a feature only available in NFSv4, it's the filesystem giving you capabilities throught a specific syscall.

**Comment by Soft** [comment]
Oh okay, I must have transferred the VM manually or something the first time, I don't remember as it was before christmas. Hmm I guess I'll have to figure out why NFS v4 is breaking.

**Comment by mdontu** [comment]
I have seen those error messages when using an AppArmor-enabled kernel (4.14 or later). libvirt needs some extra "magic" to create a proper AppArmor rule for qemu.

I seem to remember Canonical pushing their latest AA changes upstream which broke a bunch of stuffs because it added extra checks that people were not expecting.

**Comment by Wenzel** [comment]
> Hmm I guess I'll have to figure out why NFS v4 is breaking.
NFSv4 requires more permissions on the filesystem.

i captured the network with wireshark to understand why Vagrant failed to connect to the NFS, it was a directory permission issue.
i chmod it to 755 and it was working after that.

I think we should keep NFSv4 if possible, otherwise the QEMU builds will break.
Let me test again with NFSv3

**Comment by Wenzel** [comment]
The vagrantfile will soon be updated to Debian Buster.
Closing this PR has it has been opened since a long time now and may not be relevant anymore.

**Pull request closed without merging**
